services:
	mariadb:
		build:
			context: ./requirements/mariadb
		image: mariadb:1.0
		restart: unless-stopped
		secrets:
			- mariadb_database
			- mariadb_user
			- mariadb_password
			- mariadb_root_password
		environment:
			MARIADB_DATABASE_FILE: /run/secrets/mariadb_database
			MARIADB_USER_FILE: /run/secrets/mariadb_user
			MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
			MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
		volumes:
			- mariadb_data:/var/lib/mysql
		networks:
			- inception

volumes:
	mariadb_data:
		name: mariadb_data

networks:
	inception:
		name: inception
		driver: bridge

secrets:
	mariadb_database:
		file: ../secrets/mariadb_database.txt
	mariadb_user:
		file: ../secrets/mariadb_user.txt
	mariadb_password:
		file: ../secrets/mariadb_password.txt
	mariadb_root_password:
		file: ../secrets/mariadb_root_password.txt
